### ISSUE TITLE
Get personal profile with zeabur profile command

### ISSUE THREAD

**Issue by MichaelYuhe** [zeabur/cli#66]

**Comment by ErKiran** [comment]
@MichaelYuhe 
Could you kindly provide more details about the information required for the 'profile' command? 

For instance:

- Is the required information limited to basic user details?

- Or should it encompass a summarized profile, including details on current projects, subscription information, etc.?
Your clarification will be immensely helpful.

Thank you

**Comment by MichaelYuhe** [comment]
I've reviewed and merged your pull request! Thanks so much. I will add a more detailed description in my future issues
