### ISSUE TITLE
Document behavior that `zeabur` deploys the current directory as service

### ISSUE THREAD

**Issue by LaoshuBaby** [zeabur/cli#87]
### Describe the bug

![图片](https://github.com/zeabur/cli/assets/42690037/06c737fd-f8ad-4fec-a5eb-c914ed70cc3c)

### Additional context

output:

```
PS C:\Users\laoshubaby> zeabur
INFO    A browser window will be opened for you to login, please confirm
INFO    Select one project to deploy your service.
INFO    Only one project found, select <savits> automatically

INFO    Only one environment in current project, select <production> automatically

INFO    Select one service to deploy or create a new one.
Current working directory:  C:\Users\laoshubaby
Error packing current directory to zip file!!!
ERROR   open .local\share\wezterm\gui-sock-30056: The file cannot be accessed by the system.
```

If you need debug logs please tell me where to find them and I will provide them to you as soon as possible

---
Version：zeabur_0.2.2-beta1_windows_amd64
System: Windows 11 Insider Preview 10.0.26020 Build 26020.rs_prerelease.231214.

Related discussion on Discord: https://discord.com/channels/1060209568820494336/1207325547789819954/1207329807755513887

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pan93412** [comment]
Seems like you are attempting to upload your home directory as a Zeabur service. It is usually not expected and you should run `zeabur` on the root directory of *your project*.

If you are curious about why Zeabur ate so much – we compress your project files in memory, so the 8GB is basically the (incomplete) compressed size of your home directory.

**Comment by pan93412** [comment]
We have documented this behaviour on our docs. Sorry for confusing! <https://zeabur.com/docs/deploy/deploy-in-cli>
