### ISSUE TITLE
[bug] can not logout after token expired

### ISSUE THREAD

**Issue by STRRL** [zeabur/cli#89]
### Describe the bug

```
$ zeabur auth logout             
INFO    Token is from OAuth2 and it's expired, refreshing it
ERROR   failed to refresh token, it is recommended to logout and login again: failed to refresh token: oauth2: "invalid_grant" "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client"
```

### Expected behaviour

could logout and clear my session.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by STRRL** [comment]
after remove `~/.config/zeabur/cli.yaml`, I could re-login with the cli tool.

**Comment by STRRL** [comment]
it even prevents me execute `zeabur version`..

I guess that zeabur-cli invoke the auth process too early.

**Comment by aFlyBird0** [comment]
Sorry 🥹 

But It seems that this bug has been solved on 7 Feb. (Perhaps it wasn't released when you were using it.)

<img width="1722" alt="image" src="https://github.com/zeabur/cli/assets/36830265/a6df205c-e8ed-4b30-bc4e-9a7fafede884">

**Comment by pan93412** [comment]
It has been fixed. Please update your Zeabur CLI version. Thanks for reporting!
